#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)// makes motorA and motorD both turn postive
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void dropToken( int choiceCol, bool isHumanPlaying);
void spinnerMotor(bool isHumanPlaying);
void motorHold(int col);
const int colAngle[7]=
	{0, -70, -145, -215, -300, -400, -528};


task main()
{
	//motorHold(1);
dropToken(1,true);

}

void dropToken(int choiceCol, bool isHumanPlaying)
{
	nMotorEncoder[motorA] = 0;


	for(int col =0; col < 7; col++)
	{
		if(choiceCol == col + 1)
		{
			motor[motorA] = 15;
			motor[motorD] = 15;
			while(nMotorEncoder[motorA] > colAngle[col])
			{}

			while(!getButtonPress(buttonEnter))
		{
		motorHold(col);
			}

			motor[motorA] = motor[motorD] = 0;

		}
	}
}


void motorHold(int col)
{
		while(nMotorEncoder[motorA] < colAngle[col])
		{
			motor[motorD] = -1;
			motor[motorA] = -2;
		}
		while(nMotorEncoder[motorA] > colAngle[col])
		{
			motor[motorD] = 2;
			motor[motorA] = 1;
		}
		motor[motorD] = 1;
		motor[motorA] = -1;

}
